Bug/urls.py
from django.urls import path
from . import views


app_name = 'issues'

urlpatterns = [
    path('', views.bugIndex, name='issues'),
    path('add/', views.add_issue, name='new_bug'),
    path('<int:pk>/', views.bug_detailview, name='bug_detail'),
    path('<int:pk>/notes/', views.bug_notes, name='bug_entries'),
    path('<int:pk>/notes/add/', views.add_entry, name='add_notes'),
    path('<int:pk>/notes/<int:id>/', views.entry_detail, name='bugentry_detail'),
    path('<int:pk>/notes/<int:id>/update/', views.update_entry, name='update_entry'),
    path('<int:pk>/notes/<int:id>/delete/', views.delete_entry, name='delete_entry'),
    path('<int:pk>/attachs/', views.get_bug_attachments, name='bug_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attached'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='attached_detail'),
    path('<int:pk>/attachs/update/<int:id>/', views.update_attachment, name='update_attached'),
    path('<int:pk>/attachs/delete/<int:id>/', views.delete_attachment, name='delete_attached'),
    path('update/<int:pk>/', views.update_bug, name='update_bug'),
    path('delete/<int:pk>/', views.DeleteBug.as_view(), name='delete_issue')
]

Todo/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.TD_index, name='todo'),
    path('add/', views.add_todo, name='add_todo'),
    path('<int:pk>/', views.td_detail, name='todo_detail'),
    path('<int:pk>/attachs/', views.get_task_attachments, name='task_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attach'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='attached_detail'),
    path('<int:pk>/attachs/update/<int:id>/', views.update_attachment, name='update_attached'),
    path('<int:pk>/attachs/delete/<int:id>/', views.delete_attachment, name='delete_attached'),
    path('update/<int:pk>/', views.td_update, name='update_todo'),
    path('delete/<int:pk>/', views.DeleteToDo.as_view(), name='delete_todo')
]

bugTrack_Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_view, name='home'),
    path('tracker/', include('Bug.urls', namespace='issues')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('todos/', include('Todo.urls', namespace='todos')),
    path('linktasks/', include('linkedTasks.urls', namespace='linkedtask')),
    path('knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views
from .views import SettingsView


app_name = 'settings'

urlpatterns = [
    path('', SettingsView.as_view(), name='settings'),
    path('bstatus/', views.bugstatus_list, name='bug_status'),
    path('bstatus/add/', views.add_bugstatus, name='add_bstatus'),
    path('bstatus/<int:pk>/', views.bugstatus_detail, name='bstatus_detail'),
    path('bstatus/update/<int:pk>', views.update_bugstatus, name='bstatus_update'),
    path('bstatus/delete/<int:pk>', views.delete_bugstatus, name='bstatus_delete'),
    path('bpriority/', views.bugpriority_list, name='bug_priority'),
    path('bpriority/add/', views.add_bugpriority, name='add_bpriority'),
    path('bpriority/<int:pk>/', views.bugpriority_detail, name='bpriority_detail'),
    path('bpriority/update/<int:pk>/', views.update_bugpriority, name='bpriority_update'),
    path('bpriority/delete/<int:pk>/', views.delete_td_priority, name='bpriority_delete'),
    path('bcategory/', views.bugcategory_list, name='bug_category'),
    path('bcategory/add/', views.add_bugcategory, name='add_bcategory'),
    path('bcategory/<int:pk>/', views.category_bugdetail, name='bcategory_detail'),
    path('bcategory/update/<int:pk>/', views.update_bugcategory, name='bcategory_update'),
    path('bcategory/delete/<int:pk>/', views.delete_bugcategory, name='bcategory_delete'),
    path('tdstatus/', views.td_status_list, name='td_status'),
    path('tdstatus/add/', views.add_td_status, name='add_tdstatus'),
    path('tdstatus/<int:pk>/', views.td_status_detail, name='tdstatus_detail'),
    path('tdstatus/update/<int:pk>/', views.update_td_status, name='tdstatus_update'),
    path('tdstatus/delete/<int:pk>/', views.delete_td_status, name='tdstatus_delete'),
    path('tdpriority/', views.td_priority_list, name='td_priority'),
    path('tdpriority/add/', views.add_td_priority, name='add_td_priority'),
    path('tdpriority/<int:pk>/', views.td_priority_detail, name='td_priority_detail'),
    path('tdpriority/update/<int:pk>/', views.update_td_priority, name='td_priority_update'),
    path('tdpriority/delete/<int:pk>/', views.delete_td_priority, name='td_priority_delete'),
    path('ltstatus/', views.lt_status_list, name='lt_status'),
    path('ltstatus/add/', views.add_lt_status, name='add_ltstatus'),
    path('ltstatus/<int:pk>/', views.lt_status_detail, name='ltstatus_detail'),
    path('ltstatus/update/<int:pk>/', views.update_lt_status, name='ltstatus_update'),
    path('ltstatus/delete/<int:pk>/', views.delete_lt_status, name='ltstatus_delete'),
    path('ltcategory/', views.lt_category_list, name='lt_category'),
    path('ltcategory/add/', views.add_lt_category, name='add_ltcategory'),
    path('ltcategory/<int:pk>/', views.lt_category_detail, name='ltcategory_detail'),
    path('ltcategory/update/<int:pk>/', views.update_lt_category, name='ltcategory_update'),
    path('ltcategory/delete/<int:pk>/', views.delete_lt_category, name='ltcategory_delete'),
    path('tstatus/', views.t_status_list, name='t_status'),
    path('tstatus/add/', views.add_tstatus, name='add_tstatus'),
    path('tstatus/<int:pk>/', views.t_status_detail, name='t_status_detail'),
    path('tstatus/update/<int:pk>/', views.update_tstatus, name='update_tstatus'),
    path('tstatus/delete/<int:pk>/', views.delete_tstatus, name='delete_tstatus'),
    path('trank/', views.t_rank_list, name='t_rank'),
    path('trank/add/', views.add_trank, name='add_trank'),
    path('trank/<int:pk>/', views.t_rank_detail, name='t_rank_detail'),
    path('trank/update/<int:pk>/', views.update_trank, name='update_trank'),
    path('trank/delete/<int:pk>/', views.delete_trank, name='delete_trank'),
    path('kbtype/', views.kb_type_list, name='kb_type'),
    path('kbtype/add/', views.add_kbtype, name='add_kbtype'),
    path('kbtype/<int:pk>/', views.kb_type_list, name='kb_type_detail'),
    path('kbtype/update/<int:pk>/', views.update_kbtype, name='update_kbtype'),
    path('kbtype/delete/<int:pk>/', views.delete_kbtype, name='delete_kbtype')
]

Todo/models.py
from django.db import models
from settings.models import TD_Priority, TD_Status


class ToDo(models.Model):
    name = models.CharField(max_length=55, null=False)
    priority = models.ForeignKey(TD_Priority, on_delete=models.CASCADE)
    description = models.TextField(max_length=275, null=True, blank=True)
    status = models.ForeignKey(TD_Status, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Attachment(models.Model):
    file_name = models.CharField(max_length=125, null=False)
    file = models.FileField(upload_to='attachments/', max_length=500, null=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    attached_to = models.ForeignKey(ToDo, related_name='entity', on_delete=models.CASCADE)

    objects = models.Manager()

    def __str__(self):
        return self.file_name

Todo/forms.py
from django import forms
from .models import ToDo, Attachment
from settings.models import TD_Status, TD_Priority


class TDForm(forms.ModelForm):
    name = forms.CharField(label='To Do', help_text='Name your Task ToDo',
                           widget=forms.TextInput(attrs={'class': 'text'}))
    priority = forms.ModelChoiceField(queryset=TD_Priority.objects.all(), label='Priority',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Details', widget=forms.Textarea)
    status = forms.ModelChoiceField(queryset=TD_Status.objects.all(), label='Status',
                                    widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = ToDo
        fields = ['name', 'priority', 'description', 'status', 'active']


class AttachmentForm(forms.ModelForm):

    class Meta:
        model = Attachment
        fields = ['file_name', 'file']

Todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ToDo, Attachment
from .forms import TDForm, AttachmentForm
from settings.models import TD_Priority, TD_Status
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import DeleteView


def TD_index(request):
    todos = ToDo.objects.all()
    return render(request, 'ToDo_Index.html', {'todos': todos})


def add_todo(request):
    if request.method == 'GET':
        return render(request, 'todo_form.html', {'form': TDForm})
    elif request.method == 'POST':
        form = TDForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('todos:todo'))


def td_detail(request, pk):
    td = ToDo.objects.get(pk=pk)
    context = {
        'td': td,
        'priorities': TD_Priority.objects.all(),
        'statuses': TD_Status.objects.all()
    }
    return render(request, 'todo_detail.html', context)


def td_update(request, pk):
    obj = get_object_or_404(ToDo, pk=pk)
    form = TDForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'todo_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('todos:todo_detail', kwargs={'pk': pk}))


class DeleteToDo(DeleteView):
    model = ToDo
    success_url = "/"


def get_task_attachments(request, pk):
    attachments = Attachment.objects.filter(attached_to__pk=pk)
    obj = get_object_or_404(ToDo, pk=pk)
    return render(request, 'task_attachments.html', {'attachments': attachments, 'todo': obj})


def attached_details(request, pk, id):
    entry = Attachment.objects.get(id=id)
    context = {
        'entry': entry,
        'pk': pk
    }
    return render(request, 'attached_detail.html', context)


def add_attachment(request, pk):
    if request.method == 'POST':
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = ToDo.objects.get(pk=pk)
            post.save()
            return redirect(reverse('todos:tasks_attachments', kwargs={'pk': pk}))
    else:
        form = AttachmentForm()
    return render(request, 'attach_form.html', {"form": form, 'pk': pk})


def update_attachment(request, pk, id):
    obj = get_object_or_404(Attachment, id=id)
    form = AttachmentForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'attach_form.html', {"form": form, 'pk': pk})
    elif request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = ToDo.objects.get(pk=pk)
            post.save()
            return HttpResponseRedirect(reverse('todos:attached_detail', kwargs={'id': id, 'pk': pk}))
        else:
            return render(request, 'attach_form.html', {"form": form, 'pk': pk})


def delete_attachment(request, pk, id):
    query = Attachment.objects.get(id=id)
    query.delete()
    return redirect(reverse('todos:task_attachments', kwargs={'pk': pk}))

Todo/templates/ToDo_Index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>To Do List</h1>
    <br/>
    <div class='container-fluid'>
        <div class="d-grip gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'todos:add_todo' %}" class="btn btn-primary btn-sm">Add New Issue</a>
            <a href="{% url 'settings:settings' %}" class="btn btn-secondary btn-sm">Settings</a>
        </div>
        <caption>Your To Do List</caption>
        <div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Priority</th>
                        <th>Details</th>
                        <th>Status</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {% for td in todos %}
                        <tr>
                            <td>{{td.name}}</td>
                            <td>{{td.priority}}</td>
                            <td>{{td.description}}</td>
                            <td>{{td.status}}</td>
                            <td>
                                <button class='btn btn-warning btn-sm'><a href="{% url 'todos:todo_detail' td.pk %}">View</a></button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

Todo/templates/attach_form.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
    <button class="btn btn-secondary btn-sm pull-left"><a href="{% url 'todos:task_attachments' pk %}">Back</a></button>
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Document Name: </label><br/>
        <span>{{ form.file_name }}</span>
    </div>
    <div class="form-group">
        <label>File: </label><br/>
        <span>{{ form.file }}</span>
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Save</button>
</form>

{% endblock %}

Todo/templates/attached_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <caption> {{ entry.attached_to.name }}'s Attachment </caption>
        <div class="row">
            <a href="{% url 'todos:task_attachments' pk %}"><button class="btn btn-outline-secondary btn-sm">Back</button></a>
            <a href="{% url 'todos:add_attach' pk %}"><button class="btn btn-outline-primary btn-sm">Add</button></a>
        </div>
        <div class="container" style="background-color: #DCDCDC;">
            <div>
                <label>Document Name: </label><br/>
                <span>{{ entry.file_name }}</span>
            </div>
            <br/>
            <div>
                <label>File: </label><br/>
                <span>{{ entry.file }}</span>
            </div>
            <br/>
            <div>
                <label>Uploaded At: </label><br/>
                <span>{{ entry.uploaded_at }}</span>
            </div>
        </div>
        <div class="row">
            <a href="{% url 'todos:update_attached' pk entry.id %}"><button class="btn btn-outline-warning btn-sm">Update</button></a>
            <a href="{% url 'todos:delete_attached' pk entry.id %}"><button class="btn btn-outline-danger btn-sm">Delete</button></a>
        </div>
    </div>

{% endblock %}

Todo/templates/task_attachments.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="d-grip gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'todos:todo_detail' todo.pk %}">Back</a></button>
        <button class="btn btn-outline-info btn-sm"><a href="{% url 'todos:add_attach' todo.pk %}">Add Attachment</a></button>
    </div>
    <caption>{{ todo.name }} Attachments</caption>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Document</th>
                <th>File</th>
                <th>Uploaded At</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for att in attachments %}
                <tr>
                    <td>{{ att.file_name }}</td>
                    <td>{{ att.file }}</td>
                    <td>{{ att.uploaded_at }}</td>
                    <td>
                        <a href="{% url 'todos:attached_detail' todo.pk att.id %}"><button class="btn btn-warning btn-sm">View</button></a>
                        <a href="{% url 'todos:delete_attached' todo.pk att.id %}"><button class="btn btn-warning btn-sm">Delete</button></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Todo/templates/todo_detail.html
{% load static %}

{% extends "base.html" %}
{% block content %}
<div class="container">
    <a href="{% url 'todos:todo' %}" class="btn btn-primary btn-sm">Back</a>
    <div class="form-group">
        {% csrf_token %}
        <div>
            <label>Task:</label><br/>
            <input type="text" name="name" value="{{ td.name }}"><br/>
        </div>
        <div>
            <label>Priority:</label><br/>
            <select name="priority">
                {% for priority in priorities %}
                {% if priority.priority == td.priority %}
                <option value="{{ priority.priority }}" selected>{{ priority.priority }}</option>
                {% else %}
                <option value="{{ priority.priority }}">{{ priority.priority }}</option>
                {% endif %}
                {% endfor %}
            </select><br/>
        </div>
        <div>
            <label>Details:</label><br/>
            <textarea style="border: 1px solid black;">{{ td.description }}</textarea><br/>
        </div>
        <div>
            <label>Status:</label><br>
            <select name="status">
                {% for status in statuses %}
                {% if status.status == td.status %}
                <option value="{{ status.status}}" selected>{{ status.status }}</option>
                {% else %}
                <option value="{{ status.status }}">{{ status.status }}</option>
                {% endif %}
                {% endfor %}
            </select><br/>
        </div>
    </div>
    <div class="btn-group btn-group-sm">
        <button class="btn btn-warning"><a href="{% url 'todos:update_todo' td.pk %}">Update</a></button>
        <br>
        <button class="btn btn-alert"><a href="{% url 'todos:delete_todo' td.pk %}">Delete</a></button>
    </div>
</div>
{% endblock %}

Todo/templates/todo_form.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <button class="btn btn-secondary btn-sm pull-right"><a href="{% url 'todos:todo' %}">Back</a></button>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label>Task:</label><br>
        {{ form.name }}
    </div>
    <div class="form-group">
        <label>Priority:</label><br>
        {{ form.priority }}
    </div>
    <div class="form-group">
        <label>Details: </label><br>
        {{ form.description }}
    </div>
    <div class="form-group">
        <label>Status: </label><br>
        {{ form.status }}
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</form>

{% endblock %}