Bug/urls.py
from django.urls import path
from . import views


app_name = 'issues'

urlpatterns = [
    path('', views.bugIndex, name='issues'),
    path('add/', views.add_issue, name='new_bug'),
    path('<int:pk>/', views.bug_detailview, name='bug_detail'),
    path('<int:pk>/notes/', views.bug_notes, name='bug_entries'),
    path('<int:pk>/notes/add/', views.add_entry, name='add_notes'),
    path('<int:pk>/notes/<int:id>/', views.entry_detail, name='bugentry_detail'),
    path('<int:pk>/notes/<int:id>/update/', views.update_entry, name='update_entry'),
    path('<int:pk>/notes/<int:id>/delete/', views.delete_entry, name='delete_entry'),
    path('<int:pk>/attachs/', views.get_bug_attachments, name='bug_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attached'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='attached_detail'),
    path('<int:pk>/attachs/update/<int:id>/', views.update_attachment, name='update_attached'),
    path('<int:pk>/attachs/delete/<int:id>/', views.delete_attachment, name='delete_attached'),
    path('update/<int:pk>/', views.update_bug, name='update_bug'),
    path('delete/<int:pk>/', views.DeleteBug.as_view(), name='delete_issue')
]

bugTrack_Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_view, name='home'),
    path('tracker/', include('Bug.urls', namespace='issues')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('todos/', include('Todo.urls', namespace='todos')),
    path('linktasks/', include('linkedTasks.urls', namespace='linkedtask')),
    path('knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views
from .views import SettingsView


app_name = 'settings'

urlpatterns = [
    path('', SettingsView.as_view(), name='settings'),
    path('bstatus/', views.bugstatus_list, name='bug_status'),
    path('bstatus/add/', views.add_bugstatus, name='add_bstatus'),
    path('bstatus/<int:pk>/', views.bugstatus_detail, name='bstatus_detail'),
    path('bstatus/update/<int:pk>', views.update_bugstatus, name='bstatus_update'),
    path('bstatus/delete/<int:pk>', views.delete_bugstatus, name='bstatus_delete'),
    path('bpriority/', views.bugpriority_list, name='bug_priority'),
    path('bpriority/add/', views.add_bugpriority, name='add_bpriority'),
    path('bpriority/<int:pk>/', views.bugpriority_detail, name='bpriority_detail'),
    path('bpriority/update/<int:pk>/', views.update_bugpriority, name='bpriority_update'),
    path('bpriority/delete/<int:pk>/', views.delete_td_priority, name='bpriority_delete'),
    path('bcategory/', views.bugcategory_list, name='bug_category'),
    path('bcategory/add/', views.add_bugcategory, name='add_bcategory'),
    path('bcategory/<int:pk>/', views.category_bugdetail, name='bcategory_detail'),
    path('bcategory/update/<int:pk>/', views.update_bugcategory, name='bcategory_update'),
    path('bcategory/delete/<int:pk>/', views.delete_bugcategory, name='bcategory_delete'),
    path('tdstatus/', views.td_status_list, name='td_status'),
    path('tdstatus/add/', views.add_td_status, name='add_tdstatus'),
    path('tdstatus/<int:pk>/', views.td_status_detail, name='tdstatus_detail'),
    path('tdstatus/update/<int:pk>/', views.update_td_status, name='tdstatus_update'),
    path('tdstatus/delete/<int:pk>/', views.delete_td_status, name='tdstatus_delete'),
    path('tdpriority/', views.td_priority_list, name='td_priority'),
    path('tdpriority/add/', views.add_td_priority, name='add_td_priority'),
    path('tdpriority/<int:pk>/', views.td_priority_detail, name='td_priority_detail'),
    path('tdpriority/update/<int:pk>/', views.update_td_priority, name='td_priority_update'),
    path('tdpriority/delete/<int:pk>/', views.delete_td_priority, name='td_priority_delete'),
    path('ltstatus/', views.lt_status_list, name='lt_status'),
    path('ltstatus/add/', views.add_lt_status, name='add_ltstatus'),
    path('ltstatus/<int:pk>/', views.lt_status_detail, name='ltstatus_detail'),
    path('ltstatus/update/<int:pk>/', views.update_lt_status, name='ltstatus_update'),
    path('ltstatus/delete/<int:pk>/', views.delete_lt_status, name='ltstatus_delete'),
    path('ltcategory/', views.lt_category_list, name='lt_category'),
    path('ltcategory/add/', views.add_lt_category, name='add_ltcategory'),
    path('ltcategory/<int:pk>/', views.lt_category_detail, name='ltcategory_detail'),
    path('ltcategory/update/<int:pk>/', views.update_lt_category, name='ltcategory_update'),
    path('ltcategory/delete/<int:pk>/', views.delete_lt_category, name='ltcategory_delete'),
    path('tstatus/', views.t_status_list, name='t_status'),
    path('tstatus/add/', views.add_tstatus, name='add_tstatus'),
    path('tstatus/<int:pk>/', views.t_status_detail, name='t_status_detail'),
    path('tstatus/update/<int:pk>/', views.update_tstatus, name='update_tstatus'),
    path('tstatus/delete/<int:pk>/', views.delete_tstatus, name='delete_tstatus'),
    path('trank/', views.t_rank_list, name='t_rank'),
    path('trank/add/', views.add_trank, name='add_trank'),
    path('trank/<int:pk>/', views.t_rank_detail, name='t_rank_detail'),
    path('trank/update/<int:pk>/', views.update_trank, name='update_trank'),
    path('trank/delete/<int:pk>/', views.delete_trank, name='delete_trank'),
    path('kbtype/', views.kb_type_list, name='kb_type'),
    path('kbtype/add/', views.add_kbtype, name='add_kbtype'),
    path('kbtype/<int:pk>/', views.kb_type_list, name='kb_type_detail'),
    path('kbtype/update/<int:pk>/', views.update_kbtype, name='update_kbtype'),
    path('kbtype/delete/<int:pk>/', views.delete_kbtype, name='delete_kbtype')
]

settings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView
from .models import Bug_Priority, Bug_Status, Bug_Category, TD_Priority, TD_Status, \
    T_Rank, T_Status, LT_Status, LT_Category, KB_Type
from .forms import BugStatusForm, BugCategoryForm, BugPriorityForm, StatusForm, PriorityForm, \
    TRankForm, LTStatusForm, LTCategoryForm, TStatusForm, KBTypeForm


class SettingsView(TemplateView):
    template_name = 'settingsIndex.html'


def bugstatus_list(request):
    items = Bug_Status.objects.all()
    context = {
        'itemset': 'bstatus',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def bugpriority_list(request):
    items = Bug_Priority.objects.all()
    context = {
        'itemset': 'bpriority',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def bugcategory_list(request):
    items = Bug_Category.objects.all()
    context = {
        'itemset': 'bcategory',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def bugstatus_detail(request, pk):
    status = Bug_Status.objects.get(pk=pk)
    context = {
        'item': status,
        'set': 'bstatus'
    }

    return render(request, 'setting_detail.html', context)


def update_bugstatus(request, pk):
    obj = get_object_or_404(Bug_Status, pk=pk)
    form = BugStatusForm(request.POST or None, instance=obj)
    if request.method == "GET":
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bstatus_detail', kwargs={'pk': pk}))


def bugpriority_detail(request, pk):
    priority = Bug_Priority.objects.get(pk=pk)
    context = {
        'item': priority,
        'set': 'bpriority'
    }
    return render(request, 'setting_detail.html', context)


def update_bugpriority(request, pk):
    obj = get_object_or_404(Bug_Priority, pk=pk)
    form = BugPriorityForm(request.POST or None, instance=obj)
    if request.method == "GET":
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bpriority_detail', kwargs={'pk': pk}))


def category_bugdetail(request, pk):
    category = Bug_Category.objects.get(pk=pk)
    context = {
        'item': category,
        'set': 'bcategory'
    }
    return render(request, 'setting_detail.html', context)


def update_bugcategory(request, pk):
    obj = get_object_or_404(Bug_Category, pk=pk)
    form = BugCategoryForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bcategory_detail', kwargs={'pk': pk}))


def add_bugstatus(request):
    if request.method == "GET":
        return render(request, "setting_form.html", {"form": BugStatusForm})

    elif request.method == 'POST':
        form = BugStatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bug_status'))


def add_bugpriority(request):
    if request.method == 'GET':
        return render(request, "setting_form.html", {"form": BugPriorityForm})
    elif request.method == 'POST':
        form = BugPriorityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bug_priority'))


def add_bugcategory(request):
    if request.method == 'GET':
        return render(request, "setting_form.html", {"form": BugCategoryForm})
    elif request.method == 'POST':
        form = BugCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:bug_category'))


def delete_bugstatus(request, pk):
    query = Bug_Status.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:bug_status'))


def delete_bugpriority(request, pk):
    query = Bug_Priority.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:bug_priority'))


def delete_bugcategory(request, pk):
    query = Bug_Category.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:bug_category'))


def td_priority_list(request):
    items = TD_Priority.objects.all()
    context = {
        'itemset': 'tdpriority',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def td_status_list(request):
    items = TD_Status.objects.all()
    context = {
        'itemset': 'tdstatus',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def td_priority_detail(request, pk):
    priority = TD_Priority.objects.get(pk=pk)
    context = {
        'item': priority,
        'set': 'tdpriority'
    }
    return render(request, 'setting_detail.html', context)


def td_status_detail(request, pk):
    status = TD_Status.objects.get(pk=pk)
    context = {
        'item': status,
        'set': 'tdstatus'
    }
    return render(request, 'setting_detail.html', context)


def add_td_priority(request):
    if request.method == "GET":
        return render(request, "setting_form.html", {"form": PriorityForm})
    elif request.method == 'POST':
        form = PriorityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:td_priority'))


def add_td_status(request):
    if request.method == "GET":
        return render(request, "setting_form.html", {"form": StatusForm})
    elif request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:td_status'))


def update_td_status(request, pk):
    obj = get_object_or_404(TD_Status, pk=pk)
    form = StatusForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:tdstatus_detail', kwargs={'pk': pk}))


def update_td_priority(request, pk):
    obj = get_object_or_404(TD_Priority, pk=pk)
    form = PriorityForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:td_priority_detail', kwargs={'pk': pk}))


def delete_td_status(request, pk):
    query = TD_Status.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:td_status'))


def delete_td_priority(request, pk):
    query = TD_Priority.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:td_priority'))


def lt_status_list(request):
    items = LT_Status.objects.all()
    context = {
        'itemset': 'ltstatus',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def lt_status_detail(request, pk):
    status = LT_Status.objects.get(pk=pk)
    context = {
        'item': status,
        'set': 'ltstatus'
    }
    return render(request, 'setting_detail.html', context)


def add_lt_status(request):
    if request.method == "GET":
        return render(request, "setting_form.html", {"form": LTStatusForm})
    elif request.method == 'POST':
        form = LTStatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:lt_status'))


def update_lt_status(request, pk):
    obj = get_object_or_404(LT_Status, pk=pk)
    form = LTStatusForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:ltstatus_detail', kwargs={'pk': pk}))


def delete_lt_status(request, pk):
    query = LT_Status.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:lt_status'))


def lt_category_list(request):
    items = LT_Category.objects.all()
    context = {
        'itemset': 'ltcategory',
        'items': items
    }
    return render(request, 'setting_list.html', context)


def lt_category_detail(request, pk):
    category = LT_Category.objects.get(pk=pk)
    context = {
        'item': category,
        'set': 'ltcategory'
    }
    return render(request, 'setting_detail.html', context)


def add_lt_category(request):
    if request.method == "GET":
        return render(request, "setting_form.html", {"form": LTCategoryForm})
    elif request.method == 'POST':
        form = LTCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:lt_category'))


def update_lt_category(request, pk):
    obj = get_object_or_404(LT_Category, pk=pk)
    form = LTCategoryForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'setting_form.html', {"form": form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('settings:ltcategory_detail', kwargs={'pk': pk}))


def delete_lt_category(request, pk):
    query = LT_Category.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('settings:lt_category'))


def t_status_list(request):
    items = T_Status.objects.all()
    context = {
        'itemset': 'tstatus',
        'items': items
    }
    return render(request, 'setting_list.html', context)

settings/templates/setting_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container">
    {% if set == 'tdstatus' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:td_status' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_tdstatus' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Status: </label><br/>
                {{ item.status }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:tdstatus_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:tdstatus_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'tdpriority' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:td_priority' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_td_priority' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Priority: </label><br/>
                {{ item.priority }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:td_priority_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:td_priority_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'bstatus' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:bug_status' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_bstatus' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Status: </label><br/>
                {{ item.status }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:bstatus_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:bstatus_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'bpriority' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:bug_priority' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_bpriority' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Priority: </label><br/>
                {{ item.priority }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:bpriority_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:bpriority_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'ltstatus' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:lt_status' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_ltstatus' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Status: </label><br/>
                {{ item.status }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:ltstatus_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:ltstatus_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'tstatus' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:t_status' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_tstatus' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Status: </label><br/>
                {{ item.status }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:update_tstatus' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:delete_tstatus' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'trank' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:t_rank' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_trank' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Rank: </label><br/>
                {{ item.rank }}
            </div>
            <div>
                <label>Sort Order: </label><br/>
                {{ item.sort_order }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:update_trank' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:delete_trank' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'ltcategory' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:lt_category' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_ltcategory' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>Category: </label><br/>
                {{ item.category }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:ltcategory_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:ltcategory_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% elif set == 'kbtype' %}
    <div>
        <div class="row">
            <a href="{% url 'settings:kb_type' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_kbtype' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div class="container">
            <div>
                <label>KB Type: </label><br/>
                {{ item.type }}
            </div>
        </div>
        <div class="row">
            <a href="{% url 'settings:update_kbtype' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:delete_kbtype' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% else %}
    <div>
        <div class="row">
            <a href="{% url 'settings:bug_category' %}"><button class="btn btn-primary">Back</button></a>
            <a href="{% url 'settings:add_bcategory' %}"><button class="btn btn-primary">Add New</button></a>
        </div>
        <div>
            <div class="container">
                <div>
                    <label>Category: </label><br/>
                    {{ item.category }}
                </div>
            </div>
        </div>
         <div class="row">
            <a href="{% url 'settings:bcategory_update' item.pk %}"><button class="btn btn-primary">Update</button></a>
            <a href="{% url 'settings:bcategory_delete' item.pk %}"><button class="btn btn-primary">Delete</button></a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

settings/templates/setting_form.html
{% block content %}

<button class="btn btn-outline-primary"><a href="{% url 'settings:settings' %}">Back</a></button>

<div style="background-color: #fafafa; justify-content: center;">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type='submit' class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

settings/templates/settingsIndex.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <h3>Settings</h3>
    <div class="container">
        <div class="btn-group-vertical">
            <label>Bug Tracker Options</label><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:bug_status' %}">Bug Statuses</a></button><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:bug_priority' %}">Bug Priorities</a></button><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:bug_category' %}">Bug Categories</a></button><br/>
            <br/>
            <label>To Do List Options</label><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:td_status' %}">ToDo Statuses</a></button><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:td_priority' %}">ToDo Priorities</a></button><br/>
            <br/>
            <label>Linked Tasks Options</label><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:lt_status' %}">Linked Tasks Statuses</a></button><br>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:lt_category' %}">Linked Tasks Categories</a></button><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:t_rank' %}">Linked Tasks Ranks</a></button><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:t_status' %}">Tasks Statuses</a></button><br/>
            <br/>
            <label>Knowledge Base Options</label><br/>
            <button class="btn btn-outline-secondary"><a href="{% url 'settings:kb_type' %}">KB Type</a></button><br/>
        </div>
    </div>
    <div class="row">
        <div class="mt-4">
            <br>
            <a href="{% url 'home' %}"><button class="btn btn-primary">Back</button></a>
        </div>
    </div>
{% endblock %}