Bug/urls.py
from django.urls import path
from . import views


app_name = 'issues'

urlpatterns = [
    path('', views.bugIndex, name='issues'),
    path('add/', views.add_issue, name='new_bug'),
    path('<int:pk>/', views.bug_detailview, name='bug_detail'),
    path('<int:pk>/notes/', views.bug_notes, name='bug_entries'),
    path('<int:pk>/notes/add/', views.add_entry, name='add_notes'),
    path('<int:pk>/notes/<int:id>/', views.entry_detail, name='bugentry_detail'),
    path('<int:pk>/notes/<int:id>/update/', views.update_entry, name='update_entry'),
    path('<int:pk>/notes/<int:id>/delete/', views.delete_entry, name='delete_entry'),
    path('<int:pk>/attachs/', views.get_bug_attachments, name='bug_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attached'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='attached_detail'),
    path('<int:pk>/attachs/update/<int:id>/', views.update_attachment, name='update_attached'),
    path('<int:pk>/attachs/delete/<int:id>/', views.delete_attachment, name='delete_attached'),
    path('update/<int:pk>/', views.update_bug, name='update_bug'),
    path('delete/<int:pk>/', views.DeleteBug.as_view(), name='delete_issue')
]

bugTrack_Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_view, name='home'),
    path('tracker/', include('Bug.urls', namespace='issues')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('todos/', include('Todo.urls', namespace='todos')),
    path('linktasks/', include('linkedTasks.urls', namespace='linkedtask')),
    path('knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

linkedTasks/urls.py
from django.urls import path
from . import views


app_name = 'linkedtask'


urlpatterns = [
    path('', views.linkedtaskIndex, name='linked_tasks'),
    path('add/', views.add_linked_task, name='add_linked_task'),
    path('<int:pk>/', views.linked_task_detail, name='linked_task_detail'),
    path('<int:pk>/update/', views.update_linked_task, name='update_linked_task'),
    path('<int:pk>/delete/', views.delete_linked_task, name='delete_linked_task'),
    path('<int:pk>/tasks/', views.taskIndex, name='tasks'),
    path('<int:pk>/tasks/add/', views.NewTask.as_view(), name='add_task'),
    path('<int:pk>/tasks/<int:id>/', views.task_detail, name='task_detail'),
    path('<int:pk>/tasks/<int:id>/update/', views.update_task, name='update_task'),
    path('<int:pk>/tasks/<int:id>/delete/', views.delete_task, name='delete_task'),
    path('<int:pk>/tasks/<int:id>/entries/', views.task_notes, name='task_entries'),
    path('<int:pk>/tasks/<int:id>/entries/add/', views.add_entry, name='add_entry'),
    path('<int:pk>/tasks/<int:id>/entries/<int:ix>/', views.entry_detail, name='entry_detail'),
    path('<int:pk>/tasks/<int:id>/entries/<int:ix>/update/', views.update_entry, name='update_entry'),
    path('<int:pk>/tasks/<int:id>/entries/<int:ix>/delete/', views.delete_entry, name='delete_entry'),
    path('<int:pk>/attachs/', views.lt_attachments, name='lt_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attach'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='ltattached_detail'),
    path('<int:pk>/attachs/<int:id>/update/', views.update_attachment, name='update_attach'),
    path('<int:pk>/attachs/<int:id>/delete/', views.delete_attachment, name='delete_attach')

]

settings/urls.py
from django.urls import path
from . import views
from .views import SettingsView


app_name = 'settings'

urlpatterns = [
    path('', SettingsView.as_view(), name='settings'),
    path('bstatus/', views.bugstatus_list, name='bug_status'),
    path('bstatus/add/', views.add_bugstatus, name='add_bstatus'),
    path('bstatus/<int:pk>/', views.bugstatus_detail, name='bstatus_detail'),
    path('bstatus/update/<int:pk>', views.update_bugstatus, name='bstatus_update'),
    path('bstatus/delete/<int:pk>', views.delete_bugstatus, name='bstatus_delete'),
    path('bpriority/', views.bugpriority_list, name='bug_priority'),
    path('bpriority/add/', views.add_bugpriority, name='add_bpriority'),
    path('bpriority/<int:pk>/', views.bugpriority_detail, name='bpriority_detail'),
    path('bpriority/update/<int:pk>/', views.update_bugpriority, name='bpriority_update'),
    path('bpriority/delete/<int:pk>/', views.delete_td_priority, name='bpriority_delete'),
    path('bcategory/', views.bugcategory_list, name='bug_category'),
    path('bcategory/add/', views.add_bugcategory, name='add_bcategory'),
    path('bcategory/<int:pk>/', views.category_bugdetail, name='bcategory_detail'),
    path('bcategory/update/<int:pk>/', views.update_bugcategory, name='bcategory_update'),
    path('bcategory/delete/<int:pk>/', views.delete_bugcategory, name='bcategory_delete'),
    path('tdstatus/', views.td_status_list, name='td_status'),
    path('tdstatus/add/', views.add_td_status, name='add_tdstatus'),
    path('tdstatus/<int:pk>/', views.td_status_detail, name='tdstatus_detail'),
    path('tdstatus/update/<int:pk>/', views.update_td_status, name='tdstatus_update'),
    path('tdstatus/delete/<int:pk>/', views.delete_td_status, name='tdstatus_delete'),
    path('tdpriority/', views.td_priority_list, name='td_priority'),
    path('tdpriority/add/', views.add_td_priority, name='add_td_priority'),
    path('tdpriority/<int:pk>/', views.td_priority_detail, name='td_priority_detail'),
    path('tdpriority/update/<int:pk>/', views.update_td_priority, name='td_priority_update'),
    path('tdpriority/delete/<int:pk>/', views.delete_td_priority, name='td_priority_delete'),
    path('ltstatus/', views.lt_status_list, name='lt_status'),
    path('ltstatus/add/', views.add_lt_status, name='add_ltstatus'),
    path('ltstatus/<int:pk>/', views.lt_status_detail, name='ltstatus_detail'),
    path('ltstatus/update/<int:pk>/', views.update_lt_status, name='ltstatus_update'),
    path('ltstatus/delete/<int:pk>/', views.delete_lt_status, name='ltstatus_delete'),
    path('ltcategory/', views.lt_category_list, name='lt_category'),
    path('ltcategory/add/', views.add_lt_category, name='add_ltcategory'),
    path('ltcategory/<int:pk>/', views.lt_category_detail, name='ltcategory_detail'),
    path('ltcategory/update/<int:pk>/', views.update_lt_category, name='ltcategory_update'),
    path('ltcategory/delete/<int:pk>/', views.delete_lt_category, name='ltcategory_delete'),
    path('tstatus/', views.t_status_list, name='t_status'),
    path('tstatus/add/', views.add_tstatus, name='add_tstatus'),
    path('tstatus/<int:pk>/', views.t_status_detail, name='t_status_detail'),
    path('tstatus/update/<int:pk>/', views.update_tstatus, name='update_tstatus'),
    path('tstatus/delete/<int:pk>/', views.delete_tstatus, name='delete_tstatus'),
    path('trank/', views.t_rank_list, name='t_rank'),
    path('trank/add/', views.add_trank, name='add_trank'),
    path('trank/<int:pk>/', views.t_rank_detail, name='t_rank_detail'),
    path('trank/update/<int:pk>/', views.update_trank, name='update_trank'),
    path('trank/delete/<int:pk>/', views.delete_trank, name='delete_trank'),
    path('kbtype/', views.kb_type_list, name='kb_type'),
    path('kbtype/add/', views.add_kbtype, name='add_kbtype'),
    path('kbtype/<int:pk>/', views.kb_type_list, name='kb_type_detail'),
    path('kbtype/update/<int:pk>/', views.update_kbtype, name='update_kbtype'),
    path('kbtype/delete/<int:pk>/', views.delete_kbtype, name='delete_kbtype')
]

linkedTasks/forms.py
from django import forms
from .models import LinkedTasks, Entry, Attachment, Task
from settings.models import LT_Status, LT_Category, T_Status, T_Rank


class LinkedTaskForm(forms.ModelForm):
    title = forms.CharField(label='Task List', help_text='Name your Task ToDo',
                            widget=forms.TextInput(attrs={'class': 'text'}))
    summary = forms.CharField(label='Details', widget=forms.Textarea)
    category = forms.ModelChoiceField(queryset=LT_Category.objects.all(), label='Category',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    status = forms.ModelChoiceField(queryset=LT_Status.objects.all(), label='Status',
                                    widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = LinkedTasks
        fields = ['title', 'summary', 'category', 'status', 'active']


TYPES_CHOICE = (
    ("1", "To Do"),
    ("2", "Issue"),
    ("3", "Standard"),
    ("4", "Other")
)


class TaskForm(forms.ModelForm):
    name = forms.CharField(label='Task', widget=forms.TextInput(attrs={'class': 'form-control'}))
    linked_to = forms.ModelChoiceField(queryset=LinkedTasks.objects.all(), label='Linked Task List',
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    type = forms.ChoiceField(choices=TYPES_CHOICE, label='Task Type',
                             widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Details', widget=forms.Textarea)
    rank = forms.ModelChoiceField(queryset=T_Rank.objects.all(), label='Task Rank',
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    status = forms.ModelChoiceField(queryset=T_Status.objects.all(), label='Task Rank',
                                    widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Task
        fields = ['name', 'linked_to', 'type', 'description', 'rank', 'status', 'active']


class EntryForm(forms.ModelForm):
    notes = forms.CharField(label='Details', widget=forms.Textarea)
    entry_on = forms.ModelChoiceField(queryset=Task.objects.all(), label='Task',
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Entry
        fields = ['notes', 'entry_on']


class AttachmentForm(forms.ModelForm):

    class Meta:
        model = Attachment
        fields = ['file_name', 'file']

linkedTasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View

from .models import LinkedTasks, Task, Entry, Attachment
from .forms import LinkedTaskForm, TaskForm, EntryForm, AttachmentForm
from settings.models import LT_Status, LT_Category, T_Status, T_Rank


def linkedtaskIndex(request):
    lk_tasks = LinkedTasks.objects.all()
    return render(request, 'linked_tasks.html', {'lts': lk_tasks})


def linked_task_detail(request, pk):
    lt = LinkedTasks.objects.get(pk=pk)
    context = {
        'lt': lt,
        'ltstatus': LT_Status,
        'ltgategory': LT_Category
    }
    return render(request, 'linkedtask_detail.html', context)


def add_linked_task(request):
    if request.method == 'GET':
        return render(request, 'linked_task_form.html', {'form': LinkedTaskForm})
    elif request.method == 'POST':
        form = LinkedTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('linkedtask:linked_tasks'))


def update_linked_task(request, pk):
    obj = get_object_or_404(LinkedTasks, pk=pk)
    form = LinkedTaskForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'linked_task_form.html', {'form': form})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('linkedtask:linked_task_detail', kwargs={'pk': pk}))


def delete_linked_task(request, pk):
    query = LinkedTasks.objects.get(pk=pk)
    query.delete()
    return redirect(reverse('linkedtask:linked_tasks'))


def taskIndex(request, pk):
    tasks = Task.objects.filter(linked_to__pk=pk)
    obj = get_object_or_404(LinkedTasks, pk=pk)
    return render(request, 'tasks.html', {'tasks': tasks, 'linked_list': obj})


def task_detail(request, pk, id):
    task = Task.objects.get(id=id)
    types = ['To Do', 'Issue', 'Standard', 'Other']
    context ={
        'task': task,
        'linked': LinkedTasks.objects.get(pk=pk),
        'ranks': T_Rank.objects.all(),
        'statuses': T_Status.objects.all(),
        'types': types
    }
    return render(request, 'task_detail.html', context)


# def add_task(request, pk):
#     if request.method == 'GET':
#         return render(request, 'task_form.html', {'form': TaskForm, 'pk': pk})
#     elif request.method == 'POST':
#         form = TaskForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.linked_to = LinkedTasks.objects.get(pk=pk)
#             post.save()
#             return redirect(reverse('linkedtask:tasks', kwargs={'pk': pk}))


# def add_task(request, pk):
#     lt = get_object_or_404(LinkedTasks, pk=pk)
#     if request.method == 'POST':
#         form = TaskForm(request.POST)
#         if form.is_valid():
#             task = form.save(commit=False)
#             task.linked_to = lt
#             task.save()
#             return redirect(reverse('linkedtask:tasks', kwargs={'pk': pk}))
#     else:
#         form = TaskForm()
#     return render(request, 'task_form.html', {'form': form, 'pk': pk})

class NewTask(View):
    def render(self, request, pk):
        return render(request, 'task_form.html', {'form': self.form, 'pk': pk})

    def post(self, request, pk):
        self.form = TaskForm(request.POST)
        if self.form.is_valid():
            task = self.form.save(commit=False)
            task.linked_to__pk = pk
            task.save()
            return redirect(reverse('linkedtask:tasks', kwargs={'pk': pk}))
        return self.render(request, pk)

    def get(self, request, pk):
        self.form = TaskForm()
        return self.render(request, pk)


def update_task(request, pk, id):
    obj = get_object_or_404(Task, id=id)
    form = TaskForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'task_form.html', {'form': form, 'pk': pk})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('linkedtask:task_detail', kwargs={'pk': pk, 'id': id}))


def delete_task(request, pk, id):
    query = Task.objects.get(id=id)
    query.delete()
    return redirect(reverse('linkedtask:tasks', kwargs={'pk': pk}))


def task_notes(request, id):
    notes = Entry.objects.filter(entry_for__pk=id)
    obj = get_object_or_404(Task, id)
    return render(request, 'task_entries.html', {'notes': notes, 'obj': obj})


def entry_detail(request, id, ix):
    entry = Entry.objects.get(id=ix)
    return render(request, 'entry_detail.html', {'id': id, 'entry': entry})


def add_entry(request, id):
    obj = get_object_or_404(Task, id)
    if request.method == 'GET':
        return render(request, 'entry_form.html', {'form': EntryForm, 'obj': obj})
    elif request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            form.save()
            return render(reverse('linkedtask:task_entries', kwargs={'obj': obj}))


def update_entry(request, id, ix):
    obj = get_object_or_404(Entry, id=ix)
    form = EntryForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'entry_form.html', {"form": form, 'id': id})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('linkedtask:entry_detail', kwargs={'id': id, 'ix': ix}))


def delete_entry(request, id, ix):
    query = Entry.objects.get(id=ix)
    query.delete()
    return redirect(reverse('linkedtask:task_entries', kwargs={'id': id}))


def lt_attachments(request, pk):
    attachments = Attachment.objects.filter(attached_to__pk=pk)
    obj = get_object_or_404(LinkedTasks, pk=pk)
    return render(request, 'lt_attachments.html', {'attachments': attachments, 'linked': obj})


def attached_details(request, pk, id):
    attach = Attachment.objects.get(id=id)
    context = {
        'attach': attach,
        'pk': pk
    }
    return render(request, 'ltattached_detail.html', context)


def add_attachment(request, pk):
    if request.method == 'POST':
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = LinkedTasks.objects.get(pk=pk)
            post.save()
            return redirect(reverse('linkedtask:lt_attachments', kwargs={'pk': pk}))
    else:
        form = AttachmentForm()
    return render(request, 'ltattach_form.html', {'form': form, 'pk': pk})


def update_attachment(request, pk, id):
    obj = get_object_or_404(Attachment, id=id)
    form = AttachmentForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'ltattach_form.html', {"form": form, 'pk': pk})
    elif request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = LinkedTasks.objects.get(pk=pk)
            post.save()
            return HttpResponseRedirect(reverse('linkedtask:ltattached_detail', kwargs={'id': id, 'pk': pk}))
        else:
            return render(request, 'ltattach_form.html', {'form': form, 'pk': pk})


def delete_attachment(request, pk, id):
    query = Attachment.objects.get(id=id)
    query.delete()
    return redirect(reverse('linkedtask:lt_attachments', kwargs={'pk': pk}))

linkedTasks/templates/linked_tasks.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class='container-fluid'>
    <a href="{% url 'settings:settings' %}" class="btn btn-secondary btn-sm">Settings</a>
    <a href="{% url 'linkedtask:add_linked_task' %}" class="btn btn-primary btn-sm pull-right">Add New Linked List</a>
    <br/>
    <br/>
    <caption>Linked Tasks Lists</caption>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Status</th>
                <th>Created</th>
                <th>Last Updated</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for link in lts %}
            <tr>
                <td>
                    <a href="{% url 'linkedtask:linked_task_detail' link.pk %}">{{ link.title }}</a>
                </td>
                <td>
                    <a href="{% url 'linkedtask:linked_task_detail' link.pk %}">{{ link.category }}</a>
                </td>
                <td>
                    <a href="{% url 'linkedtask:linked_task_detail' link.pk %}">{{ link.status }}</a>
                </td>
                <td>
                    <a href="{% url 'linkedtask:linked_task_detail' link.pk %}">{{ link.created_at }}</a>
                </td>
                <td>
                    <a href="{% url 'linkedtask:linked_task_detail' link.pk %}">{{ link.updated_at}}</a>
                </td>
                <td>
                    <div class="btn-group btn-group-sm" role="group">
                        <a href="{% url 'linkedtask:update_linked_task' link.pk %}" class="btn btn-warning">Update</a>
                        <a href="{% url 'linkedtask:delete_linked_task' link.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

linkedTasks/templates/linkedtask_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
    <a href="{% url 'linkedtask:linked_tasks' %}" class="btn btn-secondary btn-sm pull-left">Back</a>
</div>
    <div class="card">
        <div class="card-header">
            {{ lt.title }}
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <span>{{ lt.status }}</span>
                </li>
                <li class="nav-item">
                    <a href="{% url 'linkedtask:update_linked_task' lt.pk %}" class="btn btn-warning btn-sm">Update</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'linkedtask:tasks' lt.pk %}" class="btn btn-info btn-sm pull-right">See Tasks</a>
                </li>
            </ul>
        </div>

        <div class="card body">
            <p class="card-text">{{ lt.summary }}</p>
            <div class="row">
                <div class="col-sm-3">
                    <span>{{ lt.category }}</span>
                </div>
                <div class="col-sm-3">
                    <span>Last Updated: {{ lt.updated_at }}</span>
                </div>
                <div class="col-sm-3">
                    <a href="{% url 'linkedtask:delete_linked_task' lt.pk %}" class="btn btn-danger btn-sm pull-right">Delete</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

linkedTasks/templates/lt_attachments.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 col-md-5 col-lg-6">
                <h3> {{ linked.name }} Attachments</h3>
            </div>
            <div class="col-sm-6 col-md-5 offset-md-2 col-lg-6 offset-lg-0">
                <a href="{% url 'linkedtask:linked_task_detail' linked.pk %}" class="btn btn-secondary btn-sm">Back</a>
                <a href="{% url 'linkedtask:add_attach' linked.pk %}" class="btn btn-secondary btn-sm">Add New Attachment</a>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Document</th>
                        <th>File</th>
                        <th>Uploaded At</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {% for att in attachments %}
                        <tr>
                            <td><a href="{% url 'linkedtask:attached_detail' linked.pk, att.id %}">{{ att.file_name }}</a></td>
                            <td><a href="{% url 'linkedtask:attached_detail' linked.pk, att.id %}">{{ att.file }}</a></td>
                            <td><a href="{% url 'linkedtask:attached_detail' linked.pk, att.id %}">{{ att.uploaded_at }}</a></td>
                            <td>
                                <a href="{% url 'linkedtask:update_attached' linked.pk, att.id %}" class="btn btn-warning btn-sm">Edit</a>
                                <a href="{% url 'linkedtask:delete_attached' linked.pk, att.id %}" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

linkedTasks/templates/ltattached_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <h3>{{ attach.attached_to.name }}'s Attachment</h3>
        <div class="row">
            <a href="{% url 'linkedtask:lt_attachments' pk %}" class="btn btn-outline-secondary btn-sm">Back</a>
        </div>
        <div class="row" style="background-color: #DCDCDC;">
            <div>
                <label>Document Name:  </label><br/>
                <input type="text" name="name" value="{{ attach.file_name }}"><br/>
            </div>
            <br/>
            <div>
                <label>File: </label><br/>
                <span>{{ attach.file }}</span>
            </div>
            <br/>
            <div>
                <label>Uploaded At: </label><br/>
                <span>{{ attach.uploaded_at }}</span>
            </div>
        </div>
        <div class="row">
            <a href="{% url 'linkedtask:update_attach' pk, attach.id %}" class="btn btn-warning btn-sm">Update</a>
            <a href="{% url 'linkedtask:delete_attach' pk, attach.id %}" class="btn btn-danger btn-sm">Delete</a>
        </div>
    </div>
{% endblock %}

linkedTasks/templates/task_entries.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
    <a href="{% url 'linkedtask:tasks' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</div>
<div class="row">
    <div class="col-sm-5 col-md-6">
        <div class="row">
            <div class="col-6 col-md-4">
                <label>Linked List: </label>
                <span>{{ obj.linked_to }}</span>
                <br/>
                <label>Type: </label><br/>
                <span>{{ obj.type }}</span><br/>
                <br/>
            </div>
            <div class="col-12 col-md-8">
                <span>{{ obj.name }}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-6 col-md-4">
                <label>Rank: </label><br/>
                <span>{{ obj.rank }}</span><br/>
                <label>Status: </label><br/>
                <span>{{ obj.status }}</span><br/>
            </div>
            <div class="col-12 col-md-8">
                <label>Description: </label><br/>
                <textarea style="border: 1px solid black;">{{ obj.description }}</textarea><br/>
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-md-6">
        <div class="row">
            <div class="col-md-3 ml-md-auto">
                <button class="btn btn-primary btn-sm"><a href="{% url 'linkedtask:add_entry' obj.id %}">Add Entry</a></button>
            </div>
        </div>
        <caption>Entries</caption>
        {% for note in notes %}
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-right">
                <span>Last Updated: ></span><span>{{ note.updated_at }}</span>
                <button class="btn btn-warning btn-sm"><a href="{% url 'linkedtask:update_entry' obj.id, note.pk %}">Update</a></button>
            </div>
            <div class="card-body">
                <textarea style="border: 1px solid black;">{{ note.notes }}</textarea><br/>
                <div class="row">
                    <div class="col-auto mr-auto">
                        <button class="btn btn-primary btn-sm"><a href="{% url 'linkedtask:delete_entry' obj.id, note.pk %}">Delete</a></button>
                    </div>
                    <div class="col-md-4 ml-auto">
                        <p class="card-text">Created: </p><span>{{ note.created_at }}</span>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

linkedTasks/templates/tasks.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="row">
    <a href="{% url 'linkedtask:linked_tasks' %}" class="btn btn-secondary btn-sm">Back</a>
</div>
<div class="row">
    <div class="col-8">
        <span>{{ linked_list.title }}</span>
    </div>
    <div class="col-2"></div>
    <div class="col-2">
        <a href="{% url 'linkedtask:add_task' linked_list.pk %}" class="btn btn-primary btn-sm">Add Task</a>
        <button class="btn btn-secondary btn-sm"></button>
    </div>
</div>
<div>
    {% for task in tasks %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ task.name }}</h5>
            <div>
                <div class="col-md-4">
                    <span>{{ task.rank }}</span><br/>
                    <span>{{ task.status }}</span><br/>
                </div>
                <div class="col-md-4 offset-md-4">
                    <textarea>{{ task.description }}</textarea>
                    <div class="row">
                        {{ task.updated_at }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}