Bug/urls.py
from django.urls import path
from . import views


app_name = 'issues'

urlpatterns = [
    path('', views.bugIndex, name='issues'),
    path('add/', views.add_issue, name='new_bug'),
    path('<int:pk>/', views.bug_detailview, name='bug_detail'),
    path('<int:pk>/notes/', views.bug_notes, name='bug_entries'),
    path('<int:pk>/notes/add/', views.add_entry, name='add_notes'),
    path('<int:pk>/notes/<int:id>/', views.entry_detail, name='bugentry_detail'),
    path('<int:pk>/notes/<int:id>/update/', views.update_entry, name='update_entry'),
    path('<int:pk>/notes/<int:id>/delete/', views.delete_entry, name='delete_entry'),
    path('<int:pk>/attachs/', views.get_bug_attachments, name='bug_attachments'),
    path('<int:pk>/attachs/add/', views.add_attachment, name='add_attached'),
    path('<int:pk>/attachs/<int:id>/', views.attached_details, name='attached_detail'),
    path('<int:pk>/attachs/update/<int:id>/', views.update_attachment, name='update_attached'),
    path('<int:pk>/attachs/delete/<int:id>/', views.delete_attachment, name='delete_attached'),
    path('update/<int:pk>/', views.update_bug, name='update_bug'),
    path('delete/<int:pk>/', views.DeleteBug.as_view(), name='delete_issue')
]

bugTrack_Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_view, name='home'),
    path('tracker/', include('Bug.urls', namespace='issues')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('todos/', include('Todo.urls', namespace='todos')),
    path('linktasks/', include('linkedTasks.urls', namespace='linkedtask')),
    path('knowledgebase/', include('knowledge_base.urls', namespace='knowledgebase'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views
from .views import SettingsView


app_name = 'settings'

urlpatterns = [
    path('', SettingsView.as_view(), name='settings'),
    path('bstatus/', views.bugstatus_list, name='bug_status'),
    path('bstatus/add/', views.add_bugstatus, name='add_bstatus'),
    path('bstatus/<int:pk>/', views.bugstatus_detail, name='bstatus_detail'),
    path('bstatus/update/<int:pk>', views.update_bugstatus, name='bstatus_update'),
    path('bstatus/delete/<int:pk>', views.delete_bugstatus, name='bstatus_delete'),
    path('bpriority/', views.bugpriority_list, name='bug_priority'),
    path('bpriority/add/', views.add_bugpriority, name='add_bpriority'),
    path('bpriority/<int:pk>/', views.bugpriority_detail, name='bpriority_detail'),
    path('bpriority/update/<int:pk>/', views.update_bugpriority, name='bpriority_update'),
    path('bpriority/delete/<int:pk>/', views.delete_td_priority, name='bpriority_delete'),
    path('bcategory/', views.bugcategory_list, name='bug_category'),
    path('bcategory/add/', views.add_bugcategory, name='add_bcategory'),
    path('bcategory/<int:pk>/', views.category_bugdetail, name='bcategory_detail'),
    path('bcategory/update/<int:pk>/', views.update_bugcategory, name='bcategory_update'),
    path('bcategory/delete/<int:pk>/', views.delete_bugcategory, name='bcategory_delete'),
    path('tdstatus/', views.td_status_list, name='td_status'),
    path('tdstatus/add/', views.add_td_status, name='add_tdstatus'),
    path('tdstatus/<int:pk>/', views.td_status_detail, name='tdstatus_detail'),
    path('tdstatus/update/<int:pk>/', views.update_td_status, name='tdstatus_update'),
    path('tdstatus/delete/<int:pk>/', views.delete_td_status, name='tdstatus_delete'),
    path('tdpriority/', views.td_priority_list, name='td_priority'),
    path('tdpriority/add/', views.add_td_priority, name='add_td_priority'),
    path('tdpriority/<int:pk>/', views.td_priority_detail, name='td_priority_detail'),
    path('tdpriority/update/<int:pk>/', views.update_td_priority, name='td_priority_update'),
    path('tdpriority/delete/<int:pk>/', views.delete_td_priority, name='td_priority_delete'),
    path('ltstatus/', views.lt_status_list, name='lt_status'),
    path('ltstatus/add/', views.add_lt_status, name='add_ltstatus'),
    path('ltstatus/<int:pk>/', views.lt_status_detail, name='ltstatus_detail'),
    path('ltstatus/update/<int:pk>/', views.update_lt_status, name='ltstatus_update'),
    path('ltstatus/delete/<int:pk>/', views.delete_lt_status, name='ltstatus_delete'),
    path('ltcategory/', views.lt_category_list, name='lt_category'),
    path('ltcategory/add/', views.add_lt_category, name='add_ltcategory'),
    path('ltcategory/<int:pk>/', views.lt_category_detail, name='ltcategory_detail'),
    path('ltcategory/update/<int:pk>/', views.update_lt_category, name='ltcategory_update'),
    path('ltcategory/delete/<int:pk>/', views.delete_lt_category, name='ltcategory_delete'),
    path('tstatus/', views.t_status_list, name='t_status'),
    path('tstatus/add/', views.add_tstatus, name='add_tstatus'),
    path('tstatus/<int:pk>/', views.t_status_detail, name='t_status_detail'),
    path('tstatus/update/<int:pk>/', views.update_tstatus, name='update_tstatus'),
    path('tstatus/delete/<int:pk>/', views.delete_tstatus, name='delete_tstatus'),
    path('trank/', views.t_rank_list, name='t_rank'),
    path('trank/add/', views.add_trank, name='add_trank'),
    path('trank/<int:pk>/', views.t_rank_detail, name='t_rank_detail'),
    path('trank/update/<int:pk>/', views.update_trank, name='update_trank'),
    path('trank/delete/<int:pk>/', views.delete_trank, name='delete_trank'),
    path('kbtype/', views.kb_type_list, name='kb_type'),
    path('kbtype/add/', views.add_kbtype, name='add_kbtype'),
    path('kbtype/<int:pk>/', views.kb_type_list, name='kb_type_detail'),
    path('kbtype/update/<int:pk>/', views.update_kbtype, name='update_kbtype'),
    path('kbtype/delete/<int:pk>/', views.delete_kbtype, name='delete_kbtype')
]

Bug/models.py
from django.db import models
from .managers import BugManager, EntryManager, AttachmentManager
from settings.models import Bug_Status, Bug_Category, Bug_Priority


class Bug(models.Model):
    name = models.CharField(max_length=50, null=False)
    priority = models.ForeignKey(Bug_Priority, on_delete=models.CASCADE)
    description = models.TextField(max_length=275, null=True, blank=True)
    status = models.ForeignKey(Bug_Status, on_delete=models.CASCADE)
    category = models.ForeignKey(Bug_Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = BugManager()

    def __str__(self):
        return self.name


class Entry(models.Model):
    notes = models.TextField(max_length=550, null=True, blank=True)
    entry_for = models.ForeignKey(Bug, related_name="noted_on", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = EntryManager()

    def __str__(self):
        return self.notes


class Attachment(models.Model):
    file_name = models.CharField(max_length=125, null=False)
    file = models.FileField(upload_to='attachments', max_length=500, null=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    attached_to = models.ForeignKey(Bug, related_name='entity', on_delete=models.CASCADE)

    objects = AttachmentManager()

    def __str__(self):
        return self.file_name

Bug/forms.py
from django import forms
from .models import Bug, Attachment, Entry
from settings.models import Bug_Category, Bug_Status, Bug_Priority


class BugForm(forms.ModelForm):
    name = forms.CharField(label='Summary', help_text='short description')
    priority = forms.ModelChoiceField(queryset=Bug_Priority.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Description', help_text='long description',
                                  widget=forms.Textarea)
    status = forms.ModelChoiceField(queryset=Bug_Status.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control'}))
    category = forms.ModelChoiceField(queryset=Bug_Category.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Bug
        fields = ['name', 'priority', 'description', 'status', 'category', 'active']


class AttachmentForm(forms.ModelForm):

    class Meta:
        model = Attachment
        fields = ['file_name', 'file']


class EntryForm(forms.ModelForm):
    notes = forms.CharField(label='Notes', widget=forms.Textarea(attrs={'class': 'form-control'}))
    entry_for = forms.ModelChoiceField(queryset=Bug.objects.all(), label='Bug',
                                       widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Entry
        fields = ['notes', 'entry_for']

Bug/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Bug, Attachment, Entry
from settings.models import Bug_Category, Bug_Status, Bug_Priority
from .forms import BugForm, AttachmentForm, EntryForm
from django.urls import reverse
from django.views.generic.edit import DeleteView


def bugIndex(request):
    bugs = Bug.objects.all()
    return render(request, 'bugIndex.html', {'bugs': bugs})


def add_issue(request):
    if request.method == "GET":
        return render(request, "bugcreate.html", {"form": BugForm})
    elif request.method == 'POST':
        form = BugForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('issues:issues'))


def bug_detailview(request, pk):
    bug = Bug.objects.get_by_pk(pk)
    context = {
        'bug': bug,
        'statuses': Bug_Status.objects.list(),
        'priorities': Bug_Priority.objects.list(),
        'categories': Bug_Category.objects.list()
    }
    return render(request, 'bug_detail.html', context)


def update_bug(request, pk):
    context = {}
    obj = Bug.objects.get_by_pk(pk)
    form = BugForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return HttpResponse("/"+pk)
    context['form'] = form
    return render(request, 'bug_update.html', context)


class DeleteBug(DeleteView):
    model = Bug
    success_url = "/"


def get_bug_attachments(request, pk):
    attachments = Attachment.objects.get_by_related_pk(pk)
    obj = Bug.objects.get_by_pk(pk)
    return render(request, 'attachments.html', {'attachments': attachments, 'bug': obj})


def attached_details(request, pk, id):
    entry = Attachment.objects.get(id=id)
    context = {
        'entry': entry,
        'pk': pk
    }
    return render(request, 'attached_detail.html', context)


def add_attachment(request, pk):
    if request.method == 'POST':
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = Bug.objects.get(pk=pk)
            post.save()
            return redirect(reverse('issues:bug_attachments', kwargs={'pk': pk}))
    else:
        form = AttachmentForm()
    return render(request, 'attachment_form.html', {"form": form, 'pk': pk})


def update_attachment(request, pk, id):
    obj = get_object_or_404(Attachment, id=id)
    form = AttachmentForm(request.POST or None, instance=obj)
    if request.method == 'GET':
        return render(request, 'attachment_form.html', {"form": form, 'pk': pk})
    elif request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.attached_to = Bug.objects.get(pk=pk)
            post.save()
            return HttpResponseRedirect(reverse('issues:attached_entries', kwargs={'id': id, 'pk': pk}))
        else:
            return render(request, 'attachment_form.html', {"form": form, 'pk': pk})


def delete_attachment(request, pk, id):
    query = Attachment.objects.get(id=id)
    query.delete()
    return redirect(reverse('issues:bug_attachments', kwargs={'pk': pk}))


def bug_notes(request, pk):
    notes = Entry.objects.get_by_related_pk(pk)
    bug = Bug.objects.get_by_pk(pk)
    return render(request, 'bug_entries.html', {'notes': notes, 'bug': bug})


def entry_detail(request, pk, id):
    entry = Entry.objects.get(id=id)
    return render(request, 'bugentry_detail.html', {'pk': pk, 'entry': entry})


def add_entry(request, pk):
    if request.method == 'GET':
        obj = Bug.objects.get(pk=pk)
        return render(request, 'bugentry_form.html', {'form': EntryForm, 'bug': obj})
    elif request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.entry_for = Bug.objects.get(pk=pk)
            post.save()
            return redirect(reverse('issues:bug_entries', kwargs={'pk': pk}))


def update_entry(request, pk, id):
    obj = get_object_or_404(Entry, id=id)
    form = EntryForm(request.POST or None, instance=obj)
    bug = Bug.objects.get(pk=pk)
    if request.method == 'GET':
        return render(request, 'bugentry_form.html', {'form': form, 'bug': bug})
    elif request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('issues:bug_entries', kwargs={'pk': pk}))


def delete_entry(requests, pk, id):
    query = Entry.objects.get(id=id)
    query.delete()
    return redirect(reverse('issues:bug_entries', kwargs={'pk': pk}))

Bug/templates/attached_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <caption> {{ entry.attached_to.name }}'s Attachment </caption>
        <div class="row">
            <a href="{% url 'issues:bug_attachments' pk %}"><button class="btn btn-outline-secondary btn-sm">Back</button></a>
            <a href="{% url 'issues:add_attached' pk %}"><button class="btn btn-outline-primary btn-sm">Add</button></a>
        </div>
        <div class="container" style="background-color: #DCDCDC;">
            <div>
                <label>Document Name: </label><br/>
                <span>{{ entry.file_name }}</span>
            </div>
            <br/>
            <div>
                <label>File: </label><br/>
                <span>{{ entry.file }}</span>
            </div>
            <br/>
            <div>
                <label>Uploaded At: </label><br/>
                <span>{{ entry.uploaded_at }}</span>
            </div>
        </div>
        <div class="row">
            <a href="{% url 'issues:update_attached' pk entry.id %}"><button class="btn btn-outline-warning btn-sm">Update</button></a>
            <a href="{% url 'issues:delete_attached' pk entry.id %}"><button class="btn btn-outline-danger btn-sm">Delete</button></a>
        </div>
    </div>
{% endblock %}

Bug/templates/attachment_form.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <button class="btn btn-secondary btn-sm pull-left"><a href="{% url 'issues:bug_attachments' pk %}">Back</a></button>
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Document Name: </label><br/>
        <span>{{ form.file_name }}</span>
    </div>
    <div class="form-group">
        <label>File: </label><br/>
        <span>{{ form.file }}</span>
    </div>
    <button type="submit" class="btn btn-primary btn-sm">Save</button>
</form>
{% endblock %}

Bug/templates/attachments.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="d-grip gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'issues:bug_detail' entry_for__pk %}">Back</a></button>
        <button class="btn btn-outline-info btn-sm"><a href="{% url 'issues:add_attached' entry_for__pk %}">Add Attachment</a></button>
    </div>
    <caption>{{ entry_for__name }} Attachments</caption>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Document</th>
                <th>File</th>
                <th>Uploaded At</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for att in attachments %}
                <tr>
                    <td>{{ att.file_name }}</td>
                    <td>{{ att.file }}</td>
                    <td>{{ att.uploaded_at }}</td>
                    <td>
                        <a href="{% url 'issues:attached_detail' entry_for__pk att.id %}"><button class="btn btn-warning btn-sm">View</button></a>
                        <a href="{% url 'issues:delete_attached' entry_for__pk att.id %}"><button class="btn btn-warning btn-sm">Delete</button></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Bug/templates/bugIndex.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h3>Bug-Tracker</h3>
    <br/>
    <div class="container-fluid">
        <div class="d-grip gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'issues:new_bug' %}" class="btn btn-primary btn-sm">Add New Issue</a>
            <a href="{% url 'settings:settings' %}" class="btn btn-secondary btn-sm">Settings</a>
        </div>
        <caption>Current Bugs</caption>
        <div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Bug</th>
                    <th>Priority</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Category</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for bug in bugs %}
                <tr>
                    <td>{{bug.name}}</td>
                    <td>{{bug.priority}}</td>
                    <td>{{bug.description}}</td>
                    <td>{{bug.status}}</td>
                    <td>{{bug.category}}</td>
                    <td>
                        <a href="{% url 'issues:bug_detail' bug.pk %}" class="btn btn-warning btn-sm">View</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}

Bug/templates/bug_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div>
        <div class="btn-group btn-group-sm">
        <a href="{% url 'issues:issues' %}"><button class="btn btn-primary">Back</button></a>
        <a href="{% url 'issues:bug_attachments' bug.pk %}"><button class="btn btn-outline-primary">Attachments</button>
        <a href="{% url 'issues:bug_entries' bug.pk %}" class="btn btn-outline-info btn-sm">Notes</a>
        </div>
        <div class="form-group">
            {% csrf_token %}
            <div>
                <label>Summary:</label><br>
                <input type="text" name="name" value="{{ bug.name }}"><br>
            </div>
            <div>
                <label>Priority:</label><br>
                <select name="priority">
                    {% for priority in priorities %}
                    {% if priority.priority == bug.priority %}
                    <option value="{{ priority.priority }}" selected>{{ priority.priority }}</option>
                    {% else %}
                    <option value="{{ priority.priority }}">{{ priority.priority }}</option>
                    {% endif %}
                    {% endfor %}
                </select><br>
            </div>
            <div>
                <label>Description:</label><br>
                <textarea style="border: 1px solid black;">{{ bug.description }}</textarea><br>
            </div>
            <div>
                <label>Status</label><br>
                <select name="status">
                    {% for status in statuses %}
                    {% if status.status == bug.status %}
                    <option value="{{ status.status}}" selected>{{ status.status }}</option>
                    {% else %}
                    <option value="{{ status.status }}">{{ status.status }}</option>
                    {% endif %}
                    {% endfor %}
                </select><br>
            </div>
            <div>
                <label>Category</label><br>
                <select name="category">
                    {% for cat in categories %}
                    {% if cat.category == bug.category %}
                    <option value="{{ cat.category }}" selected>{{ cat.category }}</option>
                    {% else %}
                    <option value="{{ cat.category  }}">{{ cat.category  }}</option>
                    {% endif %}
                    {% endfor %}
                </select><br>
            </div>
        </div>
    </div>
    <div class="btn-group btn-group-sm">
        <a href="{% url 'issues:update_bug' bug.pk %}"><button class="btn btn-warning">Update</button>
        <br/>
        <a href="{% url 'issues:delete_issue' bug.pk %}"><button class="btn btn-danger">Delete</button></a>
    </div>
</div>
{% endblock %}

Bug/templates/bug_entries.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="row">
        <a href="{% url 'issues:issues' %}" class="btn btn-secondary btn-sm">Back</a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-5 col-md-6">
                <div class="row">
                    <div class="col-12 col-md-8">
                        <label>Summary: </label>
                        <span>{{ bug.name }}</span>
                    </div>
                    <div class="col-6 col-md-4">
                        <label>Category: </label><br/>
                        <span>{{ bug.category }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 col-md-4">
                        <label>Priority: </label><br/>
                        <span>{{ bug.priority }}</span><br/>
                        <label>Status: </label><br/>
                        <span>{{ bug.status }}</span><br/>
                    </div>
                    <div class="col-12 col-md-8">
                        <label>Description: </label><br/>
                        <textarea style="border: 1px solid black;">{{ bug.description }}</textarea><br/>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="row">
                    <div class="col-md-10 mr-md-auto">
                        <a href="{% url 'issues:add_notes' bug.pk %}" class="btn btn-info btn-sm">Add Note</a>

                        <caption>Note Entries</caption>
                        {% for note in notes %}
                             <div class="card">
                                <div class="card-header d-flex justify-content-between align-items-right">
                                    <span>Last Updated: {{ note.updated_at }}</span>
                                    <a href="{% url 'issues:update_entry' bug.pk note.id %}" class="btn btn-warning btn-sm">Update</a>
                                </div>
                                <div class="card-body">
                                    <textarea style="border: 1px solid black;">{{ note.notes }}</textarea>
                                    <p class="card-text">Created: {{ note.created_at }}</p>
                                    <div class="row">
                                        <div class="col-auto mr-auto">
                                            <a href="{% url 'issues:delete_entry' bug.pk note.id %}" class="btn btn-danger btn-sm">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Bug/templates/bug_update.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label>Summary:</label><br>
        <input type="text" name="name" value="{{ form.name }}"><br>
    </div>
    <div class="form-group">
        <label>Priority</label><br>
        <select name="priority">
            {% for priority in form.priority.queryset.readonly %}
            {% if priority.priority == bug.priority %}
            <option value="{{ priority.priority }}" selected>{{ priority.priority }}</option>
            {% else %}
            <option value="{{ priority.priority }}">{{ priority.priority }}</option>
            {% endif %}
            {% endfor %}
        </select><br>
    </div>
    <div class="form-group">
        <label>Description</label><br>
        <textarea style="border: 1px solid black;">{{ form.description }}</textarea><br>
    </div>
    <div class="form-group">
        <label>Status</label>
        {{ form.status }}
    </div>
    <div class="form-group">
        <label>Category</label>
        {{ form.category}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<div class="row">
    <a href="{% url 'issues:issues' %}"><button class="btn btn=primary">Cancel</button></a>
</div>
{% endblock %}

Bug/templates/bugcreate.html
{% block content %}
<div class="row">
    <a href="{% url 'issues:issues' %}"><button class="btn btn-primary">Back</button></a>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label>Summary:</label><br>
        {{ form.name }}
    </div>
    <div class="form-group">
        <label>Priority:</label><br>
        {{ form.priority }}
    </div>
    <div class="form-group">
        <label>Description:</label><br>
        {{ form.description }}
    </div>
    <div class="form-group">
        <label>Status:</label><br>
        {{ form.status }}
    </div>
    <div class="form-group">
        <label>Category:</label><br>
        {{ form.category}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

Bug/templates/bugentry_form.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="row">
        <a href="{% url 'issues:bug_entries' bug.pk %}" class="btn btn-secondary btn-sm pull-left">Back</a>
    </div>
    <div class="card">
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Notes: </label><br/>
                    {{ form.notes }}
                </div>
                <div class="form-group">
                    <label>Entry for: </label><br/>
                    {{ form.entry_for }}
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}